### PR TITLE
Fix ssl deprecate warn

### PR DESCRIPTION
**Pull request by krishnan793**
ssl.wrap_socket() is deprecated from python 3.7 (see https://docs.python.org/3/library/ssl.html#ssl.SSLSocket). Based on documentation SSLContext.wrap_socket() should be used instead.

### CODE REVIEW

**Review by auvipy — APPROVED** [review]
is it possible to add / update relevant tests as well?

**Comment by krishnan793** [comment]
> is it possible to add / update relevant tests as well?

All the existing tests are passing.

**Comment by Ape** [comment]
This needs to be released. It's not only deprecated, as of Python 3.12 the feature has been removed.

**Comment by Johnius** [comment]
@auvipy Hey! Can we by chance bump the version to release this change?

**Pull request merged**
