### PR TITLE
Removed unnecessary try/except and cleaned for some PEP8

### PR DESCRIPTION
**Pull request by warvariuc**

### CODE REVIEW

**Comment by Lawouach** [comment]
Hello,

I'm not quite sure it was a useless try/except clause. As it stands, in your code the ws object may never removed from the pool. Is that expected?

**Comment by warvariuc** [comment]
I don't quite understand what you mean.
These lines
```
if ws:
    self.server.pool.track(ws)
```
will reached in the old and new implementations only if there were no exceptions in the first 3 lines, because of this:
```
except:
   raise
```

**Comment by Lawouach** [comment]
Damn. I somehow read finally rather than else on the try/except. You are right.

**Comment by warvariuc** [comment]
Maybe there should be some logic using `finally` but I am not aware of it.

**Comment by Lawouach** [comment]
I think I need to spend some time trying to identify the key issues with error handlings and related cleanups.

**Pull request merged**
