### PR TITLE
Don't crash with broken pipe when trying to close a connection

### PR DESCRIPTION
**Pull request by cristi8**
I am still encountering this issue with the latest version of ws4py. ( #150 )

My error was:
```
INFO:ws4py:Managing websocket [Local => 127.0.0.1:8080 | Remote => 127.0.0.1:53699]
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "build/bdist.linux-x86_64/egg/ws4py/manager.py", line 310, in run
    if not ws.once():
  File "build/bdist.linux-x86_64/egg/ws4py/websocket.py", line 391, in once
    if not self.process(b):
  File "build/bdist.linux-x86_64/egg/ws4py/websocket.py", line 448, in process
    self.close(s.closing.code, s.closing.reason)
  File "build/bdist.linux-x86_64/egg/ws4py/websocket.py", line 190, in close
    self._write(self.stream.close(code=code, reason=reason).single(mask=self.stream.always_mask))
  File "build/bdist.linux-x86_64/egg/ws4py/websocket.py", line 282, in _write
    self.sock.sendall(b)
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 32] Broken pipe
```

The error was reproduced 100%.
I have a CherryPy application that sends a lot of data to clients (continuous chunks of text, around 200KB each)
I have a webpage open in the browser, with some JavaScript code for receiving data.
When I closed the webpage in the browser, my server became unresponsive after the error mentioned above.

What do you think about ignoring the error (and not crashing the server) when the server can't send the closing frame to a client?

I don't want to use ws4py in production if a user that closes a webpage crashes my backend.

### CODE REVIEW

**Comment by Lawouach** [comment]
Fair point.

Is there a chance for a test demonstrating the error?

**Comment by cristi8** [comment]
Yes,
I've created a simple code that demonstrates the error.
To test, I use CherryPy==8.1.2 and Chromium version 53.0.2785.143 on Linux Mint.

To check the code, start this script, so it will listen on 127.0.0.1:8080
Then, with Chromium (or maybe even Chrome?) go to the page, open development console and click the link.
You should see the messages coming from the server (dev tools will just display a count for the messages received, because the console logs the exact same message, so don't worry about spamming the dev-tools)

So you see the count increasing as the messages arrive.  If you close the browser window, the server will crash with Broken Pipe.

Also, as a bonus, if you Refresh the page (instead of closing the tab) while the messages are coming, the server will crash with a Timeout after some time

Here is the code:
```
#!/usr/bin/env python

# Generic imports
import logging
import threading
logger = logging.getLogger(__name__)

# Webserver imports
import cherrypy
from ws4py.server.cherrypyserver import WebSocketPlugin, WebSocketTool
from ws4py.websocket import WebSocket

# Initialize ws4py WebSocket
WebSocketPlugin(cherrypy.engine).subscribe()
cherrypy.tools.websocket = WebSocketTool()


### WebSocket ###

class MyWebSocket(WebSocket):
    def spam_client(self):
        # try...except so we don't crash the thread
        try:
            for i in range(10000):
                # Send 200 KB
                self.send('a' * 200000)
        except:
            pass
        logger.info("Spam thread finished gracefully")

    def received_message(self, message):
        t = threading.Thread(target=self.spam_client)
        t.start()


### CherryPy APP ###

class MyApp(object):
    @cherrypy.expose
    def index(self):
        return '''
        <!DOCTYPE html>
        <html>
        <body>
        <script>
        var ws = new WebSocket('ws://127.0.0.1:8080/ws');
        ws.onopen = function()
        {
            console.log("Connected");
        };

        ws.onmessage = function (evt)
        {
            var received_msg = evt.data;
            console.log("Received message of length " + received_msg.length);
        };

        ws.onclose = function()
        {
            console.log("Connection is closed. Reload the page");
        };

        function send_hello() {
            ws.send('hi');
        }
        </script>
        Open dev console and click <a href="javascript:send_hello()">Start</a>
        </body>
        </html>
        '''

    @cherrypy.expose
    def ws(self):
        pass


if __name__ == '__main__':
    logging.basicConfig(level=logging.INFO)

    conf = {
        '/ws': {
            'tools.websocket.on': True,
            'tools.websocket.handler_cls': MyWebSocket
        }
    }
    cherrypy.quickstart(MyApp(), '/', conf)
```

**Comment by Lawouach** [comment]
Yeap, reproduced. Thanks for the code snippet.

**Comment by Lawouach** [comment]
Okay, I'll take that change in because it's pretty bad to crash the websocket handler indeed. Also, it seems the client did send the closing handshake so we know it was closed even though it couldn't wait for the exchange to properly complete.

**Comment by surry** [comment]
@Lawouach - I also ran into this issue. Glad it's already been fixed! Do you know when a new release with this change will be available on pypi?

**Pull request merged**
