### PR TITLE
fix bug about sec-websocket-protocol

### PR DESCRIPTION
**Pull request by Seraphli**
fix bug when sec-websocket-protocol and sec-websocket-extensions appear in header

### CODE REVIEW

**Comment by dictoss** [comment]
**I want to you merge this PR.**

My python-3.6 websocket client application has same problem, cannot connect to websocket server implemented nodejs.

I think this problem is critical.

**My application patched this PR, can connect websocket server.**

**Please merge and as soon as possible release bugfix version this problem and some important fixes.**

**Comment by filcuc** [comment]
@Lawouach can you please fix this one? Or review it?

**Comment by filcuc** [comment]
Thank you

**Comment by Lawouach** [comment]
No pb. I will release a new version today.

**Comment by dictoss** [comment]
Thank you.

**Pull request merged**
