### PR TITLE
Retry `self.sock.recv(self.reading_buffer_size)` if we receive EINTR.

### PR DESCRIPTION
**Pull request by surajrav**
This helps to not terminate the websocket on a 'C^' or a general system interrupt.

This is basically a lower down in the implementation version of #151 since I did it in websocket.py (as I am not using manager)

### CODE REVIEW

**Comment by surajrav** [comment]
I see that the CI tests failed on this. We at freenas are building it and using it and it works just fine.

Could you point me to the part in the test that failed in some more detail and I can then further look into why it is failing.

**Comment by surajrav** [comment]
Hi, if you get a chance please lookover the above commits. They are just some pep8 fixes, cleaning up unused imports and such.

I would very much like to be in sync with your base branch and I see that there is atleast one more pull request with pep8 plus optimizations, so if you go that way please inform me and I shall rebase accordingly.

**Comment by Lawouach** [comment]
Hi,

Sorry for the lack of response, I've been very busy lately.

I'm not against most of the cleanups (though I don't usually follow the double blank lines) and I will likely accept them as-is.

Regarding the other workaround, I'm not quite okay with it however. If the socket failed, it should bubble up so that the caller makes an explicit decision about it.

**Comment by tito** [comment]
This PR include more than just the intended resolution.
I fixed it referencing this PR, but also beeing more careful about checking the e.errno, which may not exists in pyOpenSSLError.

Part of the refactoring is in conflict. Please submit a new PR with just the refactoring if you still want it. If possible, seperate the PRs to prevent the merge beeing stuck by unattented changes :)

**Comment by tito** [comment]
Thanks you for your contribution!

**Pull request closed without merging**
