### PR TITLE
Rudimentary fix and testcase for Issue #179

### PR DESCRIPTION
**Pull request by medington**
See comments and fix for #179 in 854b33b. As indicated, this fix is incomplete, but certainly better than nothing. 

Secondary commit, f84dd25, is just to make the code easier to work with. I can cherry pick just the fix if you don't want those changes as well.

### CODE REVIEW

**Comment by medington** [comment]
@Lawouach Can I please get some sort of feedback on this PR? It's a bit frustrating that I took the time to create this and haven't had even a single comment. If it will never be accepted, please just let me know so I can close it and forget about it.

**Comment by Lawouach** [comment]
Hello @medington.

I do apologise for the grief. I didn't mean to offend you on this one.

This project has been on hiatus for well over two years now and I have been quite clear I would not provide much time to it. Yesterday, I thought I'd merge PRs that were clean, yours, unfortunately wasn't any more.

That was not my intenation to spite you. 

I will have a look at your PR and see if I can merge it now.

But, this project is not receiving much time anymore and, although I can only apologise for your feelings, this is an OSS project and my time is as scarce as yours :(

**Comment by medington** [comment]
@Lawouach Thank you very much for the message. Don't worry, I didn't feel spited, just a bit confused. 

I've certainly been aware of the fact that ws4py is no longer actively maintained and would have been fine had nothing ever gotten merged from contributors. When I saw some other PR's get merged but not mine that's just what got me a bit frustrated. I thought I had done a good job of documenting and testing my changes so was baffled at what the issue was preventing it from being included along with the other PR's.

Finally, I want to thank you for being an OSS project creator. Despite the fact that you no longer actively maintain this project does not diminish your contributions to the Python community, nor does my brief feeling of frustration.

Thanks again for everything!

--Mark 😃

**Comment by Lawouach** [comment]
Thanks Mark for the words. I did it in a rush yesteday and I should have been more thoughtful.

Nothing would put me off doing OSS nor Python, don't worry. I am saddened I lost "interest" in ws4py because I keep seeing people using it and I feel dishonest in some respect because I feel I can't give them what they deserve.

I have added a note to the README so new comers get the information more clearly.

Thanks for contributing as well!

- Sylvain

**Pull request merged**
